# Generated by Django 5.1.7 on 2025-03-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=3)),
                ('destination_currency', models.CharField(max_length=3)),
                ('conversion_rate', models.DecimalField(decimal_places=6, help_text='1 unit of source_currency = X units of destination_currency', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_currency', 'destination_currency')},
            },
        ),
    ]
