# Generated by Django 5.1.7 on 2025-03-29 20:29
from decimal import Decimal

from django.db import migrations


def seed_currency_pairs(apps, schema_editor):
    CurrencyPair = apps.get_model('conversion', 'CurrencyPair')

    # GBP pairs
    CurrencyPair.objects.create(source_currency='GBP', destination_currency='USD', conversion_rate=Decimal('1.29'))
    CurrencyPair.objects.create(source_currency='GBP', destination_currency='EUR', conversion_rate=Decimal('1.20'))
    CurrencyPair.objects.create(source_currency='GBP', destination_currency='GBP', conversion_rate=Decimal('1.00'))

    # USD pairs
    CurrencyPair.objects.create(source_currency='USD', destination_currency='GBP', conversion_rate=Decimal('0.77'))
    CurrencyPair.objects.create(source_currency='USD', destination_currency='EUR', conversion_rate=Decimal('0.92'))
    CurrencyPair.objects.create(source_currency='USD', destination_currency='USD', conversion_rate=Decimal('1.00'))

    # EUR pairs
    CurrencyPair.objects.create(source_currency='EUR', destination_currency='GBP', conversion_rate=Decimal('0.84'))
    CurrencyPair.objects.create(source_currency='EUR', destination_currency='USD', conversion_rate=Decimal('1.08'))
    CurrencyPair.objects.create(source_currency='EUR', destination_currency='EUR', conversion_rate=Decimal('1.00'))


def remove_currency_pairs(apps, schema_editor):
    CurrencyPair = apps.get_model('conversion', 'CurrencyPair')
    CurrencyPair.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_currency_pairs, remove_currency_pairs),
    ]
